services:
  voguenest-api:
    build: ./VogueNest-API
    image: voguenestapi:latest
    env_file:
      - .env
    environment:
      PORT: 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - vogueshopping_network

  voguenest-frontend:
    build: ./VogueNest-Frontend
    image: voguenest-frontend:latest
    port:
      - "5137:80"
    restart: always
    networks:
      - vogueshopping_network

networks:
  vogueshopping_network:
    external: true
